name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@b594ca3c0c5f4312f9674afb91ca8d7619f9c77d
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: qe201020335
          template: classic
          config_timezone: America/Toronto
          output_action: none
          
#          base: header, activity, community, repositories
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: no
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: recently-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          
          plugin_lines: yes
          
          plugin_traffic: yes
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          path: ./github-metrics.svg
          if-no-files-found: error
          retention-days: 7
          archive: false
